package com.graphyinterface;

import data.controller.UserData;
import data.functions.GenericFunctions;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;


public class CheckIn extends javax.swing.JFrame {
    
    UIManager UI;
    
    public CheckIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabelLastName = new javax.swing.JLabel();
        jTextUserEmail = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextNumber = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jLabelRepeatPassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        jRepeatPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("♥ CheckIn");
        setName("JCheckIn"); // NOI18N
        setPreferredSize(new java.awt.Dimension(370, 570));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setFocusable(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(345, 480));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRO");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 30, 50, 30, new javax.swing.ImageIcon(getClass().getResource("/com/Images/FondoBosque.jpg"))), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(280, 415));

        jLabelName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("NOMBRE");

        jTextName.setToolTipText("Ingresa tu Nombre");
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        jLabelLastName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLastName.setText(" CORREO ELECTRONICO*");

        jTextUserEmail.setToolTipText("Debe tener mas de 1 Caracter, Sin espacios y Contener \"@\"");
        jTextUserEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUserEmailActionPerformed(evt);
            }
        });

        jLabelEmail.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmail.setText(" TELEFONO");

        jTextNumber.setToolTipText("Numero de 10 Digitos");
        jTextNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNumberKeyTyped(evt);
            }
        });

        jLabelPassword.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPassword.setText(" CONTRASEÑA*");

        jButtonSubmit.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSubmit.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("CREAR NUEVO USUARIO");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jLabelRepeatPassword.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabelRepeatPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRepeatPassword.setText(" REPETIR CONTRASEÑA*");

        jPasswordField.setToolTipText("Debe ser mayor a 5 caracteres, Sin espacios");
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jRepeatPasswordField.setToolTipText("Ingrese nuevamente su Contraseña");
        jRepeatPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRepeatPasswordFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRepeatPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRepeatPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextUserEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButtonSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLastName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRepeatPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRepeatPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
       /* UI=null;
        UI.put("OptionPane.background", new Color(204, 204, 204));
        UI.put("Panel.background", new Color(204, 204, 204));
        */
        String userName=jTextName.getText();
        String userEmail=jTextUserEmail.getText();
        String userNumber=jTextNumber.getText();
        String password=String.valueOf(jPasswordField.getPassword());
        String repeatPassword=String.valueOf(jRepeatPasswordField.getPassword());
        
        if(UserData.AddUser(userName, userEmail, password, repeatPassword, userNumber)){
            JOptionPane.showMessageDialog(null, "USUARIO CREADO", "REGISTRO EXITOSO", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }else{
            if(!UserData.validateName(userName)){
                jTextName.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            }else{
                jTextName.setBorder(javax.swing.BorderFactory.createSoftBevelBorder(BevelBorder.RAISED, Color.DARK_GRAY, Color.lightGray, Color.DARK_GRAY, Color.lightGray));
            }
            
            if(!UserData.validateEmail(userEmail)){
                jTextUserEmail.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            }else{
                jTextUserEmail.setBorder(javax.swing.BorderFactory.createSoftBevelBorder(BevelBorder.RAISED, Color.DARK_GRAY, Color.lightGray, Color.DARK_GRAY, Color.lightGray));
            }
            
            if(!UserData.validateNumber(userNumber)){
                jTextNumber.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            }else{
                jTextNumber.setBorder(javax.swing.BorderFactory.createSoftBevelBorder(BevelBorder.RAISED, Color.DARK_GRAY, Color.lightGray, Color.DARK_GRAY, Color.lightGray));
            }
            
            if(!UserData.validatePassword(password,repeatPassword)){
                jPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
                jRepeatPasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
            }else{
                jPasswordField.setBorder(javax.swing.BorderFactory.createSoftBevelBorder(BevelBorder.RAISED, Color.DARK_GRAY, Color.lightGray, Color.DARK_GRAY, Color.lightGray));
                jRepeatPasswordField.setBorder(javax.swing.BorderFactory.createSoftBevelBorder(BevelBorder.RAISED, Color.DARK_GRAY, Color.lightGray, Color.DARK_GRAY, Color.lightGray));
            }
            
            if(!UserData.DuplicateUser(userEmail)){
                JOptionPane.showMessageDialog(null, "Datos Incorrectos", "Proceso no completado", JOptionPane.QUESTION_MESSAGE);
            }else{
                jTextUserEmail.setBorder(javax.swing.BorderFactory.createLineBorder(Color.RED));
                JOptionPane.showMessageDialog(null, "El correo ya ha sido resgistrado", "Proceso no completado", JOptionPane.OK_CANCEL_OPTION);
            }
        }
        
        
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        
    }//GEN-LAST:event_jTextNameActionPerformed

    private void jTextUserEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUserEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUserEmailActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jRepeatPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRepeatPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRepeatPasswordFieldActionPerformed

    private void jTextNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumberKeyTyped
        GenericFunctions.inputOnlyNumber(evt);
    }//GEN-LAST:event_jTextNumberKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelRepeatPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jRepeatPasswordField;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextNumber;
    private javax.swing.JTextField jTextUserEmail;
    // End of variables declaration//GEN-END:variables

    
}
