/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.graphyinterface;

import com.graphyinterface.menus.PSavedPlacesPanelOption;
import data.defaultplaces.DefaultPlaces;
import java.awt.BorderLayout;

/**
 *
 * @author Camil
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BoxTouristPlaces4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        touristPlacesButton4 = new javax.swing.JButton();
        BoxSavePlaces = new javax.swing.JPanel();
        savedPlacesButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(21, 0, 21, 19, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createMatteBorder(85, 35, 49, 35, new javax.swing.ImageIcon(getClass().getResource("/com/Images/FondoBosque2.jpg"))))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(528, 510));

        BoxTouristPlaces4.setBackground(new java.awt.Color(0, 0, 0));
        BoxTouristPlaces4.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 19, new javax.swing.ImageIcon(getClass().getResource("/com/Images/FondoBosque2.jpg"))), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5))); // NOI18N
        BoxTouristPlaces4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BoxTouristPlaces4MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BoxTouristPlaces4MouseMoved(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Images/Captura (1).png"))); // NOI18N

        touristPlacesButton4.setBackground(new java.awt.Color(0, 0, 0));
        touristPlacesButton4.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        touristPlacesButton4.setForeground(new java.awt.Color(255, 255, 255));
        touristPlacesButton4.setText("DESTINOS TURISTICOS");
        touristPlacesButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touristPlacesButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoxTouristPlaces4Layout = new javax.swing.GroupLayout(BoxTouristPlaces4);
        BoxTouristPlaces4.setLayout(BoxTouristPlaces4Layout);
        BoxTouristPlaces4Layout.setHorizontalGroup(
            BoxTouristPlaces4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxTouristPlaces4Layout.createSequentialGroup()
                .addGroup(BoxTouristPlaces4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(touristPlacesButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BoxTouristPlaces4Layout.setVerticalGroup(
            BoxTouristPlaces4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoxTouristPlaces4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(touristPlacesButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        BoxSavePlaces.setBackground(new java.awt.Color(0, 0, 0));
        BoxSavePlaces.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        savedPlacesButton.setBackground(new java.awt.Color(0, 0, 0));
        savedPlacesButton.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        savedPlacesButton.setForeground(new java.awt.Color(255, 255, 255));
        savedPlacesButton.setText("DESTINOS GUARDADOS");
        savedPlacesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedPlacesButtonActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Images/mapa_brujula.jpg"))); // NOI18N

        javax.swing.GroupLayout BoxSavePlacesLayout = new javax.swing.GroupLayout(BoxSavePlaces);
        BoxSavePlaces.setLayout(BoxSavePlacesLayout);
        BoxSavePlacesLayout.setHorizontalGroup(
            BoxSavePlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(savedPlacesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6)
        );
        BoxSavePlacesLayout.setVerticalGroup(
            BoxSavePlacesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoxSavePlacesLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(savedPlacesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BoxTouristPlaces4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BoxSavePlaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BoxTouristPlaces4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BoxSavePlaces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BoxTouristPlaces4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxTouristPlaces4MouseDragged

    }//GEN-LAST:event_BoxTouristPlaces4MouseDragged

    private void BoxTouristPlaces4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoxTouristPlaces4MouseMoved
        java.awt.event.MouseEvent evt2;
        /*BoxTouristPlaces.setBorder(BorderFactory.createLineBorder(Color.CYAN, 5));
        BoxTouristPlaces.setBorder(BorderFactory.createLineBorder(Color.BLACK, 5));*/

        //BoxTouristPlaces.setBorder(BorderFactory.createLineBorder(Color.CYAN, 5));
    }//GEN-LAST:event_BoxTouristPlaces4MouseMoved

    private void savedPlacesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedPlacesButtonActionPerformed
        PSavedPlacesPanelOption savePlacesBox= new PSavedPlacesPanelOption();
        savePlacesBox.setSize(528, 510);
        savePlacesBox.setLocation(0,0);

        this.removeAll();
        this.add(savePlacesBox,BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_savedPlacesButtonActionPerformed

    private void touristPlacesButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touristPlacesButton4ActionPerformed
        //PTouristPlacesPanelOption touristPlacesList= new PTouristPlacesPanelOption(DefaultPlaces.defaultListPlaces(), modelo);
        /*touristPlacesList.setSize(528, 510);
        touristPlacesList.setLocation(0,0);

        this.removeAll();
        this.add(touristPlacesList,BorderLayout.CENTER);
        this.revalidate();
        this.repaint();*/
    }//GEN-LAST:event_touristPlacesButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoxSavePlaces;
    private javax.swing.JPanel BoxTouristPlaces4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton savedPlacesButton;
    private javax.swing.JButton touristPlacesButton4;
    // End of variables declaration//GEN-END:variables
}
