/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.graphyinterface.menus;

import com.graphyinterface.Home;
import com.model.Place;
import com.model.User;
import com.model.Vehicle;
import data.controller.UserData;
import data.defaultplaces.DefaultPlaces;
import data.functions.GenericFunctions;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JRadioButton;

public class BAddBudgetPanelOption extends javax.swing.JPanel {

    private User activeUser = UserData.getActiveUser();
    private static Place selectedPlace;
    private DefaultListModel model = new DefaultListModel();

    public BAddBudgetPanelOption() {
        initComponents();
        for (Vehicle vehicle : activeUser.exportMyVehiclesList()) {
            comboBoxChooseVehicle.addItem(vehicle.getReference() + " - " + vehicle.getType() + " - " + vehicle.getModel());
        }
        if (activeUser.getDefaultVehicle() == null) {
            selectDefaultVehicle.setEnabled(false);
        }
        jTextFuelPrice.setText(String.valueOf(activeUser.getFuelPrice()));

    }

    public static Place getSelectedPlace() {
        return selectedPlace;
    }

    public static void setSelectedPlace(Place selectedPlace) {
        BAddBudgetPanelOption.selectedPlace = selectedPlace;
    }

    public void refreshPlaceField() {
        //!jListPlaces.isSelectedIndex(0)
        if (!jListPlaces.isSelectedIndex(-1) && !jListPlaces.isSelectedIndex(0)) {
            //String place = model.getElementAt(jListPlaces.getSelectedIndex()).toString();
            String place = jListPlaces.getSelectedValue();
            System.out.println("***place: " + place);
            String[] splitPlace = place.split(" - ");
            SelectedPlace.setText(splitPlace[0] + " - " + splitPlace[2]);
            SelectedPlace.setToolTipText(splitPlace[0] + " - " + splitPlace[2]);
            
        }
    }

    //This set default the list and other components, uses by reloadList()
    public void defaultReloadList() {
        SelectedPlace.setText("");
        model.clear();
        model.addElement("♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥");
        jListPlaces.setModel(model);
        SelectedPlace.setToolTipText(null);
    }

    //This function reload the list when a radioButton is selected
    public void reloadList(JRadioButton button, List<Place> placeList) {
        if (button.isSelected()) {
            defaultReloadList();

            for (Place place : placeList) {
                model.addElement(place.getNamePlace() + "- " + place.getDepartamento() + "- " + String.valueOf(place.getDistance()) + " km");
                jListPlaces.setModel(model);
            }
        } else {
            defaultReloadList();
        }
    }

    public void defaultReportNameField() {
        reportName.setText("NOMBRE DE PRESUPUESTO");
        reportName.setForeground(Color.GRAY);
    }

    // public void 
    /*private void saveButtonEnable(){           //Maybe this functions can be use later
        if(!comboBoxTypeVehicle.getSelectedItem().equals("Seleccionar") && !jTextVehicleModel.getText().equals("") && !jTextVehiclePerformance.getText().equals("Km/Galon")){
            jSaveVehicleButton.setEnabled(true);
        }else{
            jSaveVehicleButton.setEnabled(false);
            System.out.println("*-*");
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sectionHeader = new javax.swing.JPanel();
        sectionTitle = new javax.swing.JLabel();
        backArrow = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        categorieTitle = new javax.swing.JLabel();
        modelTitle = new javax.swing.JLabel();
        fuelTitle = new javax.swing.JLabel();
        jTextFuelPrice = new javax.swing.JTextField();
        selectDefaultVehicle = new javax.swing.JCheckBox();
        jSaveBudgetButton = new javax.swing.JButton();
        jWarning = new javax.swing.JLabel();
        comboBoxChooseVehicle = new javax.swing.JComboBox<>();
        touristPlaces = new javax.swing.JRadioButton();
        savedPlaces = new javax.swing.JRadioButton();
        SelectedPlace = new javax.swing.JTextField();
        selectedPlaceTitle = new javax.swing.JLabel();
        reportName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPlaces = new javax.swing.JList<>();

        jContent.setBackground(new java.awt.Color(255, 255, 255));
        jContent.setBorder(javax.swing.BorderFactory.createMatteBorder(21, 0, 21, 19, new java.awt.Color(0, 0, 0)));
        jContent.setPreferredSize(new java.awt.Dimension(528, 509));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("DEFAULT PAGE");

        javax.swing.GroupLayout jContentLayout = new javax.swing.GroupLayout(jContent);
        jContent.setLayout(jContentLayout);
        jContentLayout.setHorizontalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jContentLayout.setVerticalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel2)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 21, 19, new java.awt.Color(0, 0, 0)));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(715, 560));

        sectionHeader.setBackground(new java.awt.Color(0, 0, 0));

        sectionTitle.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        sectionTitle.setForeground(new java.awt.Color(255, 255, 255));
        sectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sectionTitle.setText("AÑADIR PRESUPUESTOS");

        backArrow.setForeground(new java.awt.Color(255, 255, 255));
        backArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Images/Arrow.png"))); // NOI18N
        backArrow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backArrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backArrowMousePressed(evt);
            }
        });

        javax.swing.GroupLayout sectionHeaderLayout = new javax.swing.GroupLayout(sectionHeader);
        sectionHeader.setLayout(sectionHeaderLayout);
        sectionHeaderLayout.setHorizontalGroup(
            sectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sectionHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sectionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sectionHeaderLayout.setVerticalGroup(
            sectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionHeaderLayout.createSequentialGroup()
                .addComponent(sectionTitle)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(sectionHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 4, new java.awt.Color(0, 0, 0)));

        formTitle.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitle.setText("AÑADIR PRESUPUESTO");

        categorieTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        categorieTitle.setText("SELECCIONAR CATEGORIA");

        modelTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        modelTitle.setText("SELECCIONAR VEHICULO");

        fuelTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        fuelTitle.setText("VALOR DE COMBUSTIBLE");

        jTextFuelPrice.setForeground(new java.awt.Color(102, 102, 102));
        jTextFuelPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFuelPrice.setText("Precio/Galon");
        jTextFuelPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFuelPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFuelPriceFocusLost(evt);
            }
        });
        jTextFuelPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFuelPriceKeyTyped(evt);
            }
        });

        selectDefaultVehicle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        selectDefaultVehicle.setText(" Vehiculo por Defecto");
        selectDefaultVehicle.setToolTipText("Seleccionar por defecto");
        selectDefaultVehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectDefaultVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDefaultVehicleActionPerformed(evt);
            }
        });

        jSaveBudgetButton.setBackground(new java.awt.Color(0, 0, 0));
        jSaveBudgetButton.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jSaveBudgetButton.setForeground(new java.awt.Color(255, 255, 255));
        jSaveBudgetButton.setText("GUARDAR");
        jSaveBudgetButton.setPreferredSize(new java.awt.Dimension(100, 35));
        jSaveBudgetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveBudgetButtonActionPerformed(evt);
            }
        });

        jWarning.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jWarning.setForeground(new java.awt.Color(255, 51, 51));
        jWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jWarning.setText(" ");

        comboBoxChooseVehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        comboBoxChooseVehicle.setInheritsPopupMenu(true);
        comboBoxChooseVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxChooseVehicleActionPerformed(evt);
            }
        });

        touristPlaces.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        touristPlaces.setText("Destinos Turisticos");
        touristPlaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touristPlacesActionPerformed(evt);
            }
        });

        savedPlaces.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        savedPlaces.setText("Destinos Guardos");
        savedPlaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedPlacesActionPerformed(evt);
            }
        });

        SelectedPlace.setEditable(false);
        SelectedPlace.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        selectedPlaceTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        selectedPlaceTitle.setText("DESTINO SELECCIONADO");

        reportName.setForeground(new java.awt.Color(153, 153, 153));
        reportName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        reportName.setText("NOMBRE DE PRESUPUESTO");
        reportName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reportNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reportNameFocusLost(evt);
            }
        });
        reportName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                reportNameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jSaveBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fuelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFuelPrice)
                                    .addComponent(touristPlaces, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savedPlaces, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxChooseVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectedPlaceTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modelTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categorieTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(selectDefaultVehicle)
                                        .addGap(25, 25, 25))
                                    .addComponent(reportName)
                                    .addComponent(SelectedPlace, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle)
                .addGap(12, 12, 12)
                .addComponent(reportName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categorieTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(touristPlaces)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savedPlaces)
                .addGap(18, 33, Short.MAX_VALUE)
                .addComponent(selectedPlaceTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectedPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxChooseVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectDefaultVehicle)
                .addGap(18, 18, 18)
                .addComponent(fuelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFuelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSaveBudgetButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jWarning)
                .addGap(29, 29, 29))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(20, 20, 70, 20, new javax.swing.ImageIcon(getClass().getResource("/com/Images/FondoBosqueCarretera.jpg"))), new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true))); // NOI18N

        jListPlaces.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jListPlaces.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListPlaces.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListPlaces.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListPlacesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListPlaces);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sectionHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sectionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backArrowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMousePressed
        MenuBudgetsPanel menuBudgetsPanel = new MenuBudgetsPanel();
        JPanel x = PTouristPlacesPanelOption.backScreenPlacesPanelOption(menuBudgetsPanel);
        this.removeAll();
        this.add(x, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_backArrowMousePressed

    private void jSaveBudgetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveBudgetButtonActionPerformed
        activeUser.setFuelPrice(Double.parseDouble(jTextFuelPrice.getText()));
        if (!SelectedPlace.getText().isBlank() && comboBoxChooseVehicle.getSelectedIndex() != 0) {
            String selectedVehicle = String.valueOf(comboBoxChooseVehicle.getSelectedItem());
            String[] splitVehicle = selectedVehicle.split(" - ");
            System.out.println("***VEH id= " + splitVehicle[0]);
            int selectedIndex = jListPlaces.getSelectedIndex() - 1;

            if (touristPlaces.isSelected()) {
                List<Place> list = DefaultPlaces.defaultListPlaces();
                System.out.println("index list - " + selectedIndex);
                selectedPlace = list.get(selectedIndex);
            } else if (savedPlaces.isSelected()) {
                selectedPlace = activeUser.searchIndex(selectedIndex);
            }
            //default name if the report with no name
            if(reportName.getText().isBlank() || reportName.getText().equalsIgnoreCase("NOMBRE DE PRESUPUESTO")){
                reportName.setText("Default_Report ("+activeUser.getDefaultNumber()+")");
                activeUser.incrementDefaultNumber();
            }
            activeUser.addReports(activeUser.autoCompleteReports(reportName.getText(),
                    Integer.parseInt(splitVehicle[0]), selectedPlace, activeUser.getFuelPrice()));
            jWarning.setText(" ");
            Home.msgSucessfulAction("Presupuesto Guardado");
            defaultReportNameField();
            //SelectedPlace.setText("");
            comboBoxChooseVehicle.setSelectedIndex(0);
            comboBoxChooseVehicle.setEnabled(true);
            selectDefaultVehicle.setSelected(false);

        } else {
            Home.msgWarning("Complete todos los campos");
            jWarning.setText("Datos Incorrectos");
        }
    }//GEN-LAST:event_jSaveBudgetButtonActionPerformed

    private void jTextFuelPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFuelPriceFocusGained
        if (jTextFuelPrice.getText().equals(String.valueOf(activeUser.getFuelPrice()))) {
            jTextFuelPrice.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextFuelPriceFocusGained

    private void jTextFuelPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFuelPriceFocusLost
        if (jTextFuelPrice.getText().equals("")) {
            jTextFuelPrice.setText(String.valueOf(activeUser.getFuelPrice()));
            jTextFuelPrice.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jTextFuelPriceFocusLost

    private void jTextFuelPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFuelPriceKeyTyped
        GenericFunctions.inputOnlyNumber(evt);
    }//GEN-LAST:event_jTextFuelPriceKeyTyped

    private void selectDefaultVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDefaultVehicleActionPerformed
        if (selectDefaultVehicle.isSelected()) {
            for (int i = 0; i < activeUser.exportMyVehiclesList().size(); i++) {
                String vehicle = comboBoxChooseVehicle.getItemAt(i + 1);
                String[] vehicleSplit = vehicle.split(" - ");
                if (activeUser.getDefaultVehicle().getReference() == Integer.parseInt(vehicleSplit[0])) {
                    System.out.println("found");
                    comboBoxChooseVehicle.setSelectedIndex(i + 1);
                    comboBoxChooseVehicle.setEnabled(false);
                    comboBoxChooseVehicle.setToolTipText(comboBoxChooseVehicle.getItemAt(i + 1));
                    break;
                }
            }
        } else {
            comboBoxChooseVehicle.setEnabled(true);
            comboBoxChooseVehicle.setToolTipText(null);
        }
    }//GEN-LAST:event_selectDefaultVehicleActionPerformed

    private void comboBoxChooseVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxChooseVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxChooseVehicleActionPerformed

    private void touristPlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touristPlacesActionPerformed
        savedPlaces.setSelected(false);
        reloadList(touristPlaces, DefaultPlaces.defaultListPlaces());
    }//GEN-LAST:event_touristPlacesActionPerformed

    private void jListPlacesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPlacesValueChanged
        if (!jListPlaces.isSelectionEmpty()) {
            refreshPlaceField();
        }

    }//GEN-LAST:event_jListPlacesValueChanged

    private void savedPlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedPlacesActionPerformed
        touristPlaces.setSelected(false);
        reloadList(savedPlaces, activeUser.exportMyPlacesList());
    }//GEN-LAST:event_savedPlacesActionPerformed

    private void reportNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reportNameFocusGained
        if (reportName.getText().equalsIgnoreCase("NOMBRE DE PRESUPUESTO")) {
            reportName.setText("");
            reportName.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_reportNameFocusGained

    private void reportNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reportNameFocusLost
        if (reportName.getText().equalsIgnoreCase("")) {
            defaultReportNameField();
        }
    }//GEN-LAST:event_reportNameFocusLost

    private void reportNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reportNameKeyTyped
        if(reportName.getText().length() > 20){
            evt.consume();
        }
    }//GEN-LAST:event_reportNameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SelectedPlace;
    private javax.swing.JLabel backArrow;
    private javax.swing.JLabel categorieTitle;
    private javax.swing.JComboBox<String> comboBoxChooseVehicle;
    private javax.swing.JLabel formTitle;
    private javax.swing.JLabel fuelTitle;
    private javax.swing.JPanel jContent;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListPlaces;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jSaveBudgetButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFuelPrice;
    private javax.swing.JLabel jWarning;
    private javax.swing.JLabel modelTitle;
    private javax.swing.JTextField reportName;
    private javax.swing.JRadioButton savedPlaces;
    private javax.swing.JPanel sectionHeader;
    private javax.swing.JLabel sectionTitle;
    private javax.swing.JCheckBox selectDefaultVehicle;
    private javax.swing.JLabel selectedPlaceTitle;
    private javax.swing.JRadioButton touristPlaces;
    // End of variables declaration//GEN-END:variables
}
