/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.graphyinterface.menus;

import com.graphyinterface.Home;
import com.model.BudgetReport;
import com.model.User;
import data.controller.UserData;
import java.awt.BorderLayout;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class BSavedBudgetPanelOption extends javax.swing.JPanel {

    private User activeUser = UserData.getActiveUser();
    private DefaultListModel model = new DefaultListModel();
    private BudgetReport selectedReport = null;

    public BSavedBudgetPanelOption() {
        initComponents();
        loadList();
        descriptionReport.setText("\n                                  ••• DETALLES •••\n"
                + "\n\n\n\n\n\n\n\n\n\n\n\n\n\n                                          ••• FIN •••");

    }

    public void loadList() {
        model.clear();
        model.addElement("♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥");
        jReportList.setModel(model);
        loadReportList();
    }
    
    public void loadReportList(){
        for (BudgetReport report : activeUser.getBudgetReports()) {
            model.addElement(report.getReportId() + " - " + report.getReportName() + " (" + report.getStatePlace() + ")");
            jReportList.setModel(model);
        }
    }

    public void refreshPlaceField(int id) {
        for (BudgetReport report : activeUser.getBudgetReports()) {
            if (report.getReportId() == id) {
                selectedReport = report;
                break;
            }
        }
        descriptionReport.setText("\n                                  ••• DETALLES •••\n" + "\n   Nombre del reporte: " + selectedReport.getReportName()
                + "\n   Id Reporte:  " + selectedReport.getReportId() + "\n   Destino: " + selectedReport.getNamePlace() + "\n   Ciudad: " + selectedReport.getNameCity()
                + "\n   Departamento: " + selectedReport.getStatePlace() + "\n   Distancia:  " + selectedReport.getDistance() + " Km" + "\n   Id Vehiculo:  " + selectedReport.getVehicleId() + " (" + selectedReport.getVehicleType() + ")"
                + "\n   Vehiculo:  " + selectedReport.getVehicleModel() + "\n   Valor Combustible:  $" + selectedReport.getFuelPrice() + "\n   Valor de Ida:  $" + selectedReport.getTravelPrice()
                + "\n   Valor de Ida y Vuelta:  $" + selectedReport.getTravelFullTrip() + "\n\n\n                                          ••• FIN •••");

    }

    /*private void saveButtonEnable(){           //Maybe this functions can be use later
        if(!comboBoxTypeVehicle.getSelectedItem().equals("Seleccionar") && !jTextVehicleModel.getText().equals("") && !jTextVehiclePerformance.getText().equals("Km/Galon")){
            jSaveVehicleButton.setEnabled(true);
        }else{
            jSaveVehicleButton.setEnabled(false);
            System.out.println("*-*");
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sectionHeader = new javax.swing.JPanel();
        sectionTitle = new javax.swing.JLabel();
        backArrow = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        jDelReportButton = new javax.swing.JButton();
        jDelAllReportsButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jReportList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionReport = new javax.swing.JTextArea();

        jContent.setBackground(new java.awt.Color(255, 255, 255));
        jContent.setBorder(javax.swing.BorderFactory.createMatteBorder(21, 0, 21, 19, new java.awt.Color(0, 0, 0)));
        jContent.setPreferredSize(new java.awt.Dimension(528, 509));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("DEFAULT PAGE");

        javax.swing.GroupLayout jContentLayout = new javax.swing.GroupLayout(jContent);
        jContent.setLayout(jContentLayout);
        jContentLayout.setHorizontalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jContentLayout.setVerticalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel2)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(javax.swing.BorderFactory.createMatteBorder(10, 0, 21, 19, new java.awt.Color(0, 0, 0)));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(715, 560));

        sectionHeader.setBackground(new java.awt.Color(0, 0, 0));

        sectionTitle.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        sectionTitle.setForeground(new java.awt.Color(255, 255, 255));
        sectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sectionTitle.setText("MIS PRESUPUESTOS");

        backArrow.setForeground(new java.awt.Color(255, 255, 255));
        backArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Images/Arrow.png"))); // NOI18N
        backArrow.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backArrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backArrowMousePressed(evt);
            }
        });

        javax.swing.GroupLayout sectionHeaderLayout = new javax.swing.GroupLayout(sectionHeader);
        sectionHeader.setLayout(sectionHeaderLayout);
        sectionHeaderLayout.setHorizontalGroup(
            sectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sectionHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sectionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE))
        );
        sectionHeaderLayout.setVerticalGroup(
            sectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionHeaderLayout.createSequentialGroup()
                .addComponent(sectionTitle)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(sectionHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 4, new java.awt.Color(0, 0, 0)));

        formTitle.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitle.setText("REPORTES");

        jDelReportButton.setBackground(new java.awt.Color(0, 0, 0));
        jDelReportButton.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jDelReportButton.setForeground(new java.awt.Color(255, 255, 255));
        jDelReportButton.setText("ELIMINAR");
        jDelReportButton.setPreferredSize(new java.awt.Dimension(90, 22));
        jDelReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDelReportButtonActionPerformed(evt);
            }
        });

        jDelAllReportsButton.setBackground(new java.awt.Color(0, 0, 0));
        jDelAllReportsButton.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jDelAllReportsButton.setForeground(new java.awt.Color(255, 255, 255));
        jDelAllReportsButton.setText("ELIMINAR TODO");
        jDelAllReportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDelAllReportsButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jReportList.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jReportList.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jReportList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦♥♦" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jReportList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jReportList.setPreferredSize(new java.awt.Dimension(221, 20));
        jReportList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jReportListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jReportList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(formTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jDelReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDelAllReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDelReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDelAllReportsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(20, 21, 60, 21, new javax.swing.ImageIcon(getClass().getResource("/com/Images/FondoBosque2.jpg"))), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3))); // NOI18N
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(231, 330));

        descriptionReport.setEditable(false);
        descriptionReport.setBackground(new java.awt.Color(255, 255, 255));
        descriptionReport.setColumns(20);
        descriptionReport.setFont(new java.awt.Font("Serif", 0, 15)); // NOI18N
        descriptionReport.setLineWrap(true);
        descriptionReport.setRows(5);
        descriptionReport.setFocusable(false);
        jScrollPane1.setViewportView(descriptionReport);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sectionHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sectionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backArrowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backArrowMousePressed
        MenuBudgetsPanel menuBudgetsPanel = new MenuBudgetsPanel();
        JPanel x = PTouristPlacesPanelOption.backScreenPlacesPanelOption(menuBudgetsPanel);
        this.removeAll();
        this.add(x, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_backArrowMousePressed

    private void jReportListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jReportListValueChanged
        if (!jReportList.isSelectionEmpty() && jReportList.getSelectedIndex() != 0) {
            String selectedValue = jReportList.getSelectedValue();
            String[] splitValue = selectedValue.split(" - ");
            System.out.println("***id " + splitValue[0]);
            int idReport = Integer.parseInt(splitValue[0]);
            refreshPlaceField(idReport);
            jReportList.setToolTipText(jReportList.getSelectedValue());
        }
    }//GEN-LAST:event_jReportListValueChanged

    private void jDelAllReportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDelAllReportsButtonActionPerformed
        if(!activeUser.emptyBudgetsList()){
            int resp = Home.optionMsg("Esta Apunto de Eliminar Todos los Reportes, \n      Desea continuar?");
            if (resp == JOptionPane.YES_OPTION) {
                activeUser.delBudgetsList();
                loadReportList();
                Home.msgSucessfulAction("Reportes Eliminados");
            }
        }else{
            Home.msgNotSelected("No Hay Reportes Registrados.");
        }
        
    }//GEN-LAST:event_jDelAllReportsButtonActionPerformed

    private void jDelReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDelReportButtonActionPerformed
        if (!jReportList.isSelectionEmpty() && jReportList.getSelectedIndex() != 0) {
            int resp = Home.optionMsg("Desea Eliminar el Reporte?");
            if (resp == JOptionPane.YES_OPTION) {
                String selectedValue = jReportList.getSelectedValue();
                String[] splitValue = selectedValue.split(" - ");
                System.out.println("***id " + splitValue[0]);
                int idReport = Integer.parseInt(splitValue[0]);
                activeUser.delReport(idReport);
                loadReportList();
                Home.msgSucessfulAction("Reporte Eliminado");
            }
        } else {
              Home.msgNotSelected("Seleccione un Reporte");
        }
    }//GEN-LAST:event_jDelReportButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backArrow;
    private javax.swing.JTextArea descriptionReport;
    private javax.swing.JLabel formTitle;
    private javax.swing.JPanel jContent;
    private javax.swing.JButton jDelAllReportsButton;
    private javax.swing.JButton jDelReportButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JList<String> jReportList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel sectionHeader;
    private javax.swing.JLabel sectionTitle;
    // End of variables declaration//GEN-END:variables
}
