package com.graphyinterface.menus;


import com.graphyinterface.Home;
import com.graphyinterface.menus.BAddBudgetPanelOption;
import com.model.Place;
import com.model.User;
import data.controller.UserData;
import data.defaultplaces.DefaultPlaces;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;


public class BSelectecPlaceBudgetPanel extends javax.swing.JFrame {

DefaultTableModel modelo;
DefaultTableModel modelo2;
    
    
    public BSelectecPlaceBudgetPanel() {
        initComponents(); 
        this.setLocationRelativeTo(null);
        modelo=(DefaultTableModel) tblAllPlaces.getModel();
        List<Place>PlacesList= DefaultPlaces.defaultListPlaces();
        for(Place place:PlacesList){
           String[] fila={String.valueOf(place.getID()),place.getNamePlace(),place.getCiudad(),place.getDepartamento(),String.valueOf(place.getDistance())+" km"}; 
           modelo.addRow(fila);
        }
        
        modelo2= (DefaultTableModel)tblMySavedPlaces.getModel();
        Home.loadTableSavedPlaces(UserData.getActiveUser(), tblMySavedPlaces);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        sectionTitle = new javax.swing.JLabel();
        jTabbedOptions = new javax.swing.JTabbedPane();
        jAllPlacesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllPlaces = new javax.swing.JTable();
        jSelectButton1 = new javax.swing.JButton();
        SavedPlacesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMySavedPlaces = new javax.swing.JTable();
        jSelectButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BackGround.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 15, 20, 15, new java.awt.Color(0, 0, 0)));
        BackGround.setPreferredSize(new java.awt.Dimension(500, 510));

        Header.setBackground(new java.awt.Color(0, 0, 0));

        sectionTitle.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        sectionTitle.setForeground(new java.awt.Color(255, 255, 255));
        sectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sectionTitle.setText("SELECCIONAR DESTINO");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sectionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(sectionTitle)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jAllPlacesPanel.setBackground(new java.awt.Color(255, 255, 255));

        tblAllPlaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CIUDAD", "DEPARTAMENTO", "DISTANCIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAllPlaces.setGridColor(new java.awt.Color(204, 204, 204));
        tblAllPlaces.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblAllPlaces.setShowVerticalLines(true);
        tblAllPlaces.getTableHeader().setReorderingAllowed(false);
        tblAllPlaces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAllPlacesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAllPlaces);

        jSelectButton1.setBackground(new java.awt.Color(0, 0, 0));
        jSelectButton1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jSelectButton1.setForeground(new java.awt.Color(255, 255, 255));
        jSelectButton1.setText("SELECCIONAR");
        jSelectButton1.setPreferredSize(new java.awt.Dimension(106, 40));
        jSelectButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSelectButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jAllPlacesPanelLayout = new javax.swing.GroupLayout(jAllPlacesPanel);
        jAllPlacesPanel.setLayout(jAllPlacesPanelLayout);
        jAllPlacesPanelLayout.setHorizontalGroup(
            jAllPlacesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(jAllPlacesPanelLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jSelectButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jAllPlacesPanelLayout.setVerticalGroup(
            jAllPlacesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jAllPlacesPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSelectButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedOptions.addTab("       TODOS LOS DESTNOS       ", jAllPlacesPanel);

        SavedPlacesPanel.setBackground(new java.awt.Color(255, 255, 255));

        tblMySavedPlaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CIUDAD", "DEPARTAMENTO", "DISTANCIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMySavedPlaces.setGridColor(new java.awt.Color(204, 204, 204));
        tblMySavedPlaces.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tblMySavedPlaces.setShowVerticalLines(true);
        tblMySavedPlaces.getTableHeader().setReorderingAllowed(false);
        tblMySavedPlaces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMySavedPlacesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMySavedPlaces);

        jSelectButton2.setBackground(new java.awt.Color(0, 0, 0));
        jSelectButton2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jSelectButton2.setForeground(new java.awt.Color(255, 255, 255));
        jSelectButton2.setText("SELECCIONAR");

        javax.swing.GroupLayout SavedPlacesPanelLayout = new javax.swing.GroupLayout(SavedPlacesPanel);
        SavedPlacesPanel.setLayout(SavedPlacesPanelLayout);
        SavedPlacesPanelLayout.setHorizontalGroup(
            SavedPlacesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(SavedPlacesPanelLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jSelectButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SavedPlacesPanelLayout.setVerticalGroup(
            SavedPlacesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SavedPlacesPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSelectButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jTabbedOptions.addTab("DESTINOS GUARDADOS", SavedPlacesPanel);

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedOptions)
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedOptions))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAllPlacesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllPlacesMouseClicked
        //jWarning.setText(" ");
        
    }//GEN-LAST:event_tblAllPlacesMouseClicked

    private void tblMySavedPlacesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMySavedPlacesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMySavedPlacesMouseClicked

    private void jSelectButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSelectButton1ActionPerformed
        if(tblAllPlaces.getSelectedRow()<0){
            Home.msgNotSelected("Seleccione un Destino");
        }else{
            int placeId=Integer.parseInt(modelo.getValueAt(tblAllPlaces.getSelectedRow(), 0).toString());
            User user = UserData.getActiveUser();
            Place selectedPlace = user.searchPlaceID(placeId);
            BAddBudgetPanelOption.setSelectedPlace(selectedPlace);
            Home.msgSucessfulAction("El Destino ha sido Seleccionado");
            this.dispose();
        }
    }//GEN-LAST:event_jSelectButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel SavedPlacesPanel;
    private javax.swing.JPanel jAllPlacesPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSelectButton1;
    private javax.swing.JButton jSelectButton2;
    private javax.swing.JTabbedPane jTabbedOptions;
    private javax.swing.JLabel sectionTitle;
    private javax.swing.JTable tblAllPlaces;
    private javax.swing.JTable tblMySavedPlaces;
    // End of variables declaration//GEN-END:variables
}
