package com.graphyinterface.menus;

import com.graphyinterface.Home;
import static com.graphyinterface.Home.setSizePanels;
import com.model.User;
import data.controller.UserData;
import data.functions.GenericFunctions;
import java.awt.BorderLayout;
import javax.swing.border.Border;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;

public class Perfile extends javax.swing.JPanel {

    private User activeUser = UserData.getActiveUser();
    private Border border = BorderFactory.createLineBorder(Color.lightGray, 1);
    private boolean changePassword;
    private boolean editDate;

    public Perfile() {
        initComponents();
        changePassword = false;
        editDate = false;
        jUserLabel.setText(activeUser.getEmail());
        nameUserField.setText(activeUser.getName());
        notEditableColor(nameUserField);
        phoneNumberField.setText(activeUser.getNumber());
        notEditableColor(phoneNumberField);
    }

    public void defaultEditable(JTextField field) {
        field.setEditable(true);
        field.setFocusable(true);
        field.setBackground(new java.awt.Color(255, 255, 255));
        field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    }

    public void notEditableColor(JTextField field) {
        field.setBackground(new java.awt.Color(247, 247, 247));
    }

    public void reLoadPanel() {
        Perfile perf = new Perfile();
        setSizePanels(perf);
        this.removeAll();
        this.add(perf, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sectionHeader = new javax.swing.JPanel();
        sectionTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        modelTitle = new javax.swing.JLabel();
        jEditForm = new javax.swing.JButton();
        jWarning = new javax.swing.JLabel();
        nameUserField = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        jSaveForm = new javax.swing.JButton();
        jEditPassword = new javax.swing.JButton();
        passwordTitle = new javax.swing.JLabel();
        jUserLabel = new javax.swing.JLabel();
        jInputPassword = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        newPasswordTitle1 = new javax.swing.JLabel();
        newPasswordTitle2 = new javax.swing.JLabel();
        rightBackGround = new javax.swing.JLabel();
        leftBackGround = new javax.swing.JLabel();

        jContent.setBackground(new java.awt.Color(255, 255, 255));
        jContent.setBorder(javax.swing.BorderFactory.createMatteBorder(21, 0, 21, 19, new java.awt.Color(0, 0, 0)));
        jContent.setPreferredSize(new java.awt.Dimension(528, 509));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("DEFAULT PAGE");

        javax.swing.GroupLayout jContentLayout = new javax.swing.GroupLayout(jContent);
        jContent.setLayout(jContentLayout);
        jContentLayout.setHorizontalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jContentLayout.setVerticalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel2)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 21, 19, new java.awt.Color(0, 0, 0)));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(715, 560));

        sectionHeader.setBackground(new java.awt.Color(0, 0, 0));
        sectionHeader.setPreferredSize(new java.awt.Dimension(668, 40));

        sectionTitle.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        sectionTitle.setForeground(new java.awt.Color(255, 255, 255));
        sectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sectionTitle.setText("PERFIL DE USUARIO");

        javax.swing.GroupLayout sectionHeaderLayout = new javax.swing.GroupLayout(sectionHeader);
        sectionHeader.setLayout(sectionHeaderLayout);
        sectionHeaderLayout.setHorizontalGroup(
            sectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionHeaderLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(sectionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sectionHeaderLayout.setVerticalGroup(
            sectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionHeaderLayout.createSequentialGroup()
                .addComponent(sectionTitle)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        formTitle.setFont(new java.awt.Font("Roboto Black", 2, 18)); // NOI18N
        formTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formTitle.setText("MI PERFIL");

        name.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        name.setText("NOMBRE");

        modelTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        modelTitle.setText("USUARIO");

        jEditForm.setBackground(new java.awt.Color(0, 0, 0));
        jEditForm.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jEditForm.setForeground(new java.awt.Color(255, 255, 255));
        jEditForm.setText("EDITAR");
        jEditForm.setPreferredSize(new java.awt.Dimension(100, 35));
        jEditForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditFormActionPerformed(evt);
            }
        });

        jWarning.setForeground(new java.awt.Color(255, 51, 51));
        jWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jWarning.setText(" ");

        nameUserField.setEditable(false);
        nameUserField.setBackground(new java.awt.Color(255, 255, 255));
        nameUserField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameUserField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nameUserField.setFocusable(false);
        nameUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUserFieldActionPerformed(evt);
            }
        });

        phoneNumber.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        phoneNumber.setText("TELEFONO");

        phoneNumberField.setEditable(false);
        phoneNumberField.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        phoneNumberField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        phoneNumberField.setFocusable(false);
        phoneNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberFieldKeyTyped(evt);
            }
        });

        jSaveForm.setBackground(new java.awt.Color(0, 0, 0));
        jSaveForm.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jSaveForm.setForeground(new java.awt.Color(255, 255, 255));
        jSaveForm.setText("GUARDAR");
        jSaveForm.setEnabled(false);
        jSaveForm.setPreferredSize(new java.awt.Dimension(100, 35));
        jSaveForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveFormActionPerformed(evt);
            }
        });

        jEditPassword.setBackground(new java.awt.Color(204, 204, 204));
        jEditPassword.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jEditPassword.setText("CAMBIAR");
        jEditPassword.setPreferredSize(new java.awt.Dimension(100, 35));
        jEditPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditPasswordActionPerformed(evt);
            }
        });

        passwordTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        passwordTitle.setText("CAMBIAR CONTRASENA");

        jUserLabel.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserLabel.setText("MaximusMeridio@gmail.edu.co");

        jInputPassword.setForeground(new java.awt.Color(204, 204, 204));
        jInputPassword.setText("jPasswordField1");
        jInputPassword.setToolTipText("Ingrese su Contraseña");
        jInputPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInputPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jInputPasswordFocusLost(evt);
            }
        });

        jPasswordField1.setEditable(false);
        jPasswordField1.setBorder(null);
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPasswordField1.setFocusable(false);

        jPasswordField2.setEditable(false);
        jPasswordField2.setBorder(null);
        jPasswordField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPasswordField2.setFocusable(false);

        newPasswordTitle1.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N

        newPasswordTitle2.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passwordTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(modelTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nameUserField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jInputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newPasswordTitle1)
                            .addComponent(newPasswordTitle2)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jEditForm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSaveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jWarning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jUserLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(formTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formTitle)
                .addGap(18, 18, 18)
                .addComponent(modelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUserLabel)
                .addGap(18, 18, 18)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phoneNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPasswordTitle1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newPasswordTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSaveForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jWarning)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        rightBackGround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Images/FondoGrisMetal.jpg"))); // NOI18N

        leftBackGround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Images/FondoGrisMetal.jpg"))); // NOI18N
        leftBackGround.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(sectionHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sectionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 499, Short.MAX_VALUE)
                    .addComponent(leftBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jEditFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditFormActionPerformed
        defaultEditable(nameUserField);
        defaultEditable(phoneNumberField);
        jSaveForm.setEnabled(true);
        editDate = true;
    }//GEN-LAST:event_jEditFormActionPerformed

    private void nameUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameUserFieldActionPerformed

    private void jSaveFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveFormActionPerformed
        jWarning.setText(" ");
        if (changePassword) {
            if (String.valueOf(jPasswordField1.getPassword()).equals(String.valueOf(jPasswordField2.getPassword()))) {
                if (!String.valueOf(jPasswordField1.getPassword()).isBlank()) {
                    activeUser.setName(nameUserField.getText());
                    activeUser.setNumber(phoneNumberField.getText());
                    activeUser.setPassword(String.valueOf(jPasswordField1.getPassword()));
                    Home.msgSucessfulAction("Datos Actualizados");
                    reLoadPanel();
                }else if(String.valueOf(jPasswordField1.getPassword()).isBlank() && editDate){
                    activeUser.setName(nameUserField.getText());
                    activeUser.setNumber(phoneNumberField.getText());
                    Home.msgSucessfulAction("Datos Actualizados");
                    reLoadPanel();
                }else{
                    Home.msgSucessfulAction("Sin Cambios");
                    reLoadPanel();
                }                    
            } else {
                jWarning.setText("Las Contraseñas no Coinciden");
            }
        } else {
            activeUser.setName(nameUserField.getText());
            activeUser.setNumber(phoneNumberField.getText());
            Home.msgSucessfulAction("Datos Actualizados");
            reLoadPanel();
        }
        
    }//GEN-LAST:event_jSaveFormActionPerformed

    private void jEditPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditPasswordActionPerformed
        if (activeUser.getPassword().equals(String.valueOf(jInputPassword.getPassword()))) {
            
            newPasswordTitle1.setText("NUEVA CONTRASEÑA");
            defaultEditable(jPasswordField1);
            jPasswordField1.setBorder(border);

            newPasswordTitle2.setText("REPITA LA CONTRASEÑA");
            defaultEditable(jPasswordField2);
            jPasswordField2.setBorder(border);

            jSaveForm.setEnabled(true);
            changePassword = true;
        } else {
            Home.msgError("Contraseña Incorrecta");
        }
    }//GEN-LAST:event_jEditPasswordActionPerformed

    private void phoneNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberFieldKeyTyped
        GenericFunctions.inputOnlyNumber(evt);
    }//GEN-LAST:event_phoneNumberFieldKeyTyped

    private void jInputPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputPasswordFocusGained
        if(String.valueOf(jInputPassword.getPassword()).equals("jPasswordField1")){
            jInputPassword.setText("");
            jInputPassword.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jInputPasswordFocusGained

    private void jInputPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputPasswordFocusLost
        if(String.valueOf(jInputPassword.getPassword()).equals("")){
            jInputPassword.setText("jPasswordField1");
            jInputPassword.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_jInputPasswordFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel formTitle;
    private javax.swing.JPanel jContent;
    private javax.swing.JButton jEditForm;
    private javax.swing.JButton jEditPassword;
    private javax.swing.JPasswordField jInputPassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JButton jSaveForm;
    private javax.swing.JLabel jUserLabel;
    private javax.swing.JLabel jWarning;
    private javax.swing.JLabel leftBackGround;
    private javax.swing.JLabel modelTitle;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameUserField;
    private javax.swing.JLabel newPasswordTitle1;
    private javax.swing.JLabel newPasswordTitle2;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JLabel rightBackGround;
    private javax.swing.JPanel sectionHeader;
    private javax.swing.JLabel sectionTitle;
    // End of variables declaration//GEN-END:variables
}
