package com.graphyinterface.menus;

import com.graphyinterface.Home;
import static com.graphyinterface.Home.setSizePanels;
import com.model.User;
import data.controller.UserData;
import data.functions.GenericFunctions;
import java.awt.BorderLayout;
import javax.swing.border.Border;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

public class Perfile extends javax.swing.JPanel {

    private final User activeUser = UserData.getActiveUser();
    private final Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(190, 190, 190));
    private boolean changePassword;
    private int passwordSize = 0;
    private int userGender = activeUser.getGender();
    private final Icon iconMale = new ImageIcon(new ImageIcon(getClass().getResource("/com/Images/gatoSmokinRecortada70x90.jpg")).getImage().getScaledInstance(70, 90, 0));
    private final Icon iconFemale = new ImageIcon(new ImageIcon(getClass().getResource("/com/Images/gataRecortada70x90.jpg")).getImage().getScaledInstance(70, 90, 0));

    public Perfile() {
        initComponents();
        changePassword = false;
        
        if (userGender == 1) {
            UserImage.setIcon(iconMale);
            chooseMale.setSelected(true);
        } else {
            UserImage.setIcon(iconFemale);
            chooseFemale.setSelected(true);
        }
        jUserLabel.setText(activeUser.getEmail());
        nameUserField.setText(activeUser.getName());
        notEditableColor(nameUserField);
        phoneNumberField.setText(activeUser.getNumber());
        notEditableColor(phoneNumberField);
        textLastUpDate.setText(activeUser.getLastUpDate());
        textLastConection.setText(activeUser.getLastConection());
    }

    public void defaultEditable(JTextField field) {
        field.setBorder(border);
        field.setEditable(true);
        field.setFocusable(true);
        field.setForeground(new java.awt.Color(50, 50, 50));
        field.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
    }

    public void notEditableColor(JTextField field) {
        field.setForeground(new java.awt.Color(150, 150, 150));
    }

    public void reLoadPanel() {
        Perfile perf = new Perfile();
        setSizePanels(perf);
        this.removeAll();
        this.add(perf, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    public void upDateDate() {
        activeUser.setLastUpDate("Ultima Actualizacion\n  " + GenericFunctions.todayDateAndHour());
        System.out.println("--> " + activeUser.getLastUpDate());
    }

    public void enableChooseGender(String yes_not) {
        switch (yes_not.toLowerCase()) {
            case "yes":
                chooseMale.setEnabled(true);
                chooseFemale.setEnabled(true);
                break;
            case "not":
                chooseMale.setEnabled(false);
                chooseFemale.setEnabled(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jContent = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sectionHeader = new javax.swing.JPanel();
        sectionTitle = new javax.swing.JLabel();
        jForm = new javax.swing.JPanel();
        UserImage = new javax.swing.JLabel();
        jUserLabel = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        nameUserField = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JLabel();
        phoneNumberField = new javax.swing.JTextField();
        passwordTitle = new javax.swing.JLabel();
        jInputPassword = new javax.swing.JPasswordField();
        newPasswordTitle1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSaveForm = new javax.swing.JButton();
        jEditForm = new javax.swing.JButton();
        jWarning = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textLastConection = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textLastUpDate = new javax.swing.JTextArea();
        chooseMale = new javax.swing.JRadioButton();
        chooseFemale = new javax.swing.JRadioButton();
        phoneNumber1 = new javax.swing.JLabel();
        rightBackGround = new javax.swing.JLabel();
        leftBackGround = new javax.swing.JLabel();

        jContent.setBackground(new java.awt.Color(255, 255, 255));
        jContent.setBorder(javax.swing.BorderFactory.createMatteBorder(21, 0, 21, 19, new java.awt.Color(0, 0, 0)));
        jContent.setPreferredSize(new java.awt.Dimension(528, 509));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("DEFAULT PAGE");

        javax.swing.GroupLayout jContentLayout = new javax.swing.GroupLayout(jContent);
        jContent.setLayout(jContentLayout);
        jContentLayout.setHorizontalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jContentLayout.setVerticalGroup(
            jContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jContentLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel2)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(0, 0, 0));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 21, 19, new java.awt.Color(0, 0, 0)));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(715, 560));

        sectionHeader.setBackground(new java.awt.Color(0, 0, 0));
        sectionHeader.setPreferredSize(new java.awt.Dimension(668, 34));

        sectionTitle.setFont(new java.awt.Font("Serif", 3, 24)); // NOI18N
        sectionTitle.setForeground(new java.awt.Color(255, 255, 255));
        sectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sectionTitle.setText("PERFIL DE USUARIO");

        javax.swing.GroupLayout sectionHeaderLayout = new javax.swing.GroupLayout(sectionHeader);
        sectionHeader.setLayout(sectionHeaderLayout);
        sectionHeaderLayout.setHorizontalGroup(
            sectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionHeaderLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(sectionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        sectionHeaderLayout.setVerticalGroup(
            sectionHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sectionHeaderLayout.createSequentialGroup()
                .addComponent(sectionTitle)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jForm.setBackground(new java.awt.Color(255, 255, 255));
        jForm.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jForm.setPreferredSize(new java.awt.Dimension(308, 420));

        UserImage.setBackground(new java.awt.Color(204, 204, 204));
        UserImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Images/gatoSmokinRecortada70x90.jpg"))); // NOI18N
        UserImage.setOpaque(true);

        jUserLabel.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jUserLabel.setForeground(new java.awt.Color(51, 51, 51));
        jUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUserLabel.setText("MaximusMeridio@gmail.edu.co");

        name.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        name.setText("NOMBRE");

        nameUserField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        nameUserField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nameUserField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nameUserField.setFocusable(false);
        nameUserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUserFieldActionPerformed(evt);
            }
        });
        nameUserField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameUserFieldKeyTyped(evt);
            }
        });

        phoneNumber.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        phoneNumber.setText("TELEFONO");

        phoneNumberField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        phoneNumberField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        phoneNumberField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        phoneNumberField.setFocusable(false);
        phoneNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumberFieldKeyTyped(evt);
            }
        });

        passwordTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        passwordTitle.setText("CAMBIAR CONTRASENA");

        jInputPassword.setForeground(new java.awt.Color(204, 204, 204));
        jInputPassword.setText("jPasswordField1");
        jInputPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jInputPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInputPassword.setFocusable(false);
        jInputPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInputPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jInputPasswordFocusLost(evt);
            }
        });
        jInputPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jInputPasswordKeyTyped(evt);
            }
        });

        newPasswordTitle1.setFont(new java.awt.Font("Roboto Black", 3, 12)); // NOI18N

        jPasswordField1.setBorder(null);
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPasswordField1.setFocusable(false);

        jSaveForm.setBackground(new java.awt.Color(0, 0, 0));
        jSaveForm.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jSaveForm.setForeground(new java.awt.Color(255, 255, 255));
        jSaveForm.setText("GUARDAR");
        jSaveForm.setEnabled(false);
        jSaveForm.setPreferredSize(new java.awt.Dimension(100, 35));
        jSaveForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveFormActionPerformed(evt);
            }
        });

        jEditForm.setBackground(new java.awt.Color(0, 0, 0));
        jEditForm.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jEditForm.setForeground(new java.awt.Color(255, 255, 255));
        jEditForm.setText("EDITAR");
        jEditForm.setPreferredSize(new java.awt.Dimension(100, 35));
        jEditForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditFormActionPerformed(evt);
            }
        });

        jWarning.setForeground(new java.awt.Color(255, 51, 51));
        jWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jWarning.setText(" ");

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setFocusable(false);
        jScrollPane1.setOpaque(false);

        textLastConection.setColumns(4);
        textLastConection.setFont(new java.awt.Font("Serif", 0, 10)); // NOI18N
        textLastConection.setForeground(new java.awt.Color(153, 153, 153));
        textLastConection.setLineWrap(true);
        textLastConection.setRows(5);
        textLastConection.setText("Ultima Conexion\n    15/11/2023");
        textLastConection.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textLastConection.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textLastConection.setFocusable(false);
        jScrollPane1.setViewportView(textLastConection);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane2.setFocusable(false);
        jScrollPane2.setOpaque(false);

        textLastUpDate.setColumns(4);
        textLastUpDate.setFont(new java.awt.Font("Serif", 0, 10)); // NOI18N
        textLastUpDate.setForeground(new java.awt.Color(153, 153, 153));
        textLastUpDate.setLineWrap(true);
        textLastUpDate.setRows(5);
        textLastUpDate.setText("Ultima Actualizacion\n    15/11/2023");
        textLastUpDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        textLastUpDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        textLastUpDate.setFocusable(false);
        jScrollPane2.setViewportView(textLastUpDate);

        chooseMale.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        chooseMale.setForeground(new java.awt.Color(51, 51, 51));
        chooseMale.setText("Hombre");
        chooseMale.setEnabled(false);
        chooseMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseMaleActionPerformed(evt);
            }
        });

        chooseFemale.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        chooseFemale.setForeground(new java.awt.Color(51, 51, 51));
        chooseFemale.setText("Mujer");
        chooseFemale.setEnabled(false);
        chooseFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFemaleActionPerformed(evt);
            }
        });

        phoneNumber1.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        phoneNumber1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneNumber1.setText("GENERO");

        javax.swing.GroupLayout jFormLayout = new javax.swing.GroupLayout(jForm);
        jForm.setLayout(jFormLayout);
        jFormLayout.setHorizontalGroup(
            jFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFormLayout.createSequentialGroup()
                        .addGroup(jFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFormLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nameUserField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                        .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(phoneNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(newPasswordTitle1)
                                    .addComponent(passwordTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jInputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jFormLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chooseMale)
                                            .addComponent(chooseFemale)))))
                            .addGroup(jFormLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jEditForm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSaveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jFormLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jFormLayout.setVerticalGroup(
            jFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UserImage, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUserLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(name)
                .addGap(0, 0, 0)
                .addComponent(nameUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneNumber)
                .addGap(0, 0, 0)
                .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phoneNumber1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseMale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseFemale)
                .addGap(18, 18, 18)
                .addComponent(passwordTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newPasswordTitle1)
                .addGap(0, 0, 0)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSaveForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jWarning)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        rightBackGround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Images/FondoGrisMetal.jpg"))); // NOI18N
        rightBackGround.setPreferredSize(new java.awt.Dimension(180, 580));

        leftBackGround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Images/FondoGrisMetal.jpg"))); // NOI18N
        leftBackGround.setPreferredSize(new java.awt.Dimension(180, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jForm, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(rightBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(sectionHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sectionHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightBackGround, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(leftBackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jEditFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditFormActionPerformed
        defaultEditable(nameUserField);
        defaultEditable(phoneNumberField);
        jInputPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        
        enableChooseGender("yes");
        jInputPassword.setFocusable(true);
        jInputPassword.setForeground(new java.awt.Color(100, 100, 100));
        jSaveForm.setEnabled(true);
    }//GEN-LAST:event_jEditFormActionPerformed

    private void nameUserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameUserFieldActionPerformed

    private void jSaveFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveFormActionPerformed
        jWarning.setText(" ");
        if (changePassword) {
            if (String.valueOf(jInputPassword.getPassword()).equals(String.valueOf(jPasswordField1.getPassword()))) {
                if (phoneNumberField.getText().length() != 10 || nameUserField.getText().isBlank()) {
                    jWarning.setText("Campos vacios o Incorrectos");
                } else {
                    activeUser.setName(nameUserField.getText());
                    activeUser.setNumber(phoneNumberField.getText());
                    activeUser.setGender(userGender);
                    activeUser.setPassword(String.valueOf(jPasswordField1.getPassword()));
                    Home.msgSucessfulAction("Datos Actualizados");
                    upDateDate();
                    reLoadPanel();
                }
            } else {
                jWarning.setText("Las Contraseñas No Coinciden");
            }
        } else {
            if (phoneNumberField.getText().length() != 10 || nameUserField.getText().isBlank()) {
                jWarning.setText("Campos vacios o Incorrectos");
            } else {
                activeUser.setName(nameUserField.getText());
                activeUser.setNumber(phoneNumberField.getText());
                activeUser.setGender(userGender);
                Home.msgSucessfulAction("Datos Actualizados");
                upDateDate();
                reLoadPanel();
            }
        }

        /*if (changePassword) {
            if (String.valueOf(jInputPassword.getPassword()).equals(String.valueOf(jPasswordField1.getPassword()))) {
                if (String.valueOf(jPasswordField1.getPassword()).length() > 5) {
                    activeUser.setName(nameUserField.getText());
                    activeUser.setNumber(phoneNumberField.getText());
                    activeUser.setGender(userGender);
                    activeUser.setPassword(String.valueOf(jPasswordField1.getPassword()));
                    Home.msgSucessfulAction("Datos Actualizados");
                    upDateDate();
                    reLoadPanel();
                } else if (String.valueOf(jInputPassword.getPassword()).isBlank() && editDate) {
                    activeUser.setName(nameUserField.getText());
                    activeUser.setNumber(phoneNumberField.getText());
                    activeUser.setGender(userGender);
                    Home.msgSucessfulAction("Datos Actualizados");
                    upDateDate();
                    reLoadPanel();
                }
            } else {
                jWarning.setText("Las Contraseñas No Coinciden");
            }
        } else {
            if (phoneNumberField.getText().length() != 10 || nameUserField.getText().isBlank()) {
                if (phoneNumberField.getText().length() != 10) {
                    jWarning.setText("Telefono Incorrecto");
                } else {
                    jWarning.setText("No puedes dejar Campos vacios");
                }
            } else {
                activeUser.setName(nameUserField.getText());
                activeUser.setNumber(phoneNumberField.getText());
                activeUser.setGender(userGender);
                Home.msgSucessfulAction("Datos Actualizados");
                upDateDate();
                reLoadPanel();
            }
        }*/

    }//GEN-LAST:event_jSaveFormActionPerformed

    private void phoneNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberFieldKeyTyped
        GenericFunctions.inputOnlyNumber(evt);
        if (phoneNumberField.getText().length() > 9) {
            evt.consume();
        }
    }//GEN-LAST:event_phoneNumberFieldKeyTyped

    private void jInputPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputPasswordFocusGained
        if (String.valueOf(jInputPassword.getPassword()).equals("jPasswordField1")) {
            jInputPassword.setText("");
            jInputPassword.setForeground(Color.BLACK);
        }
        if (String.valueOf(jInputPassword.getPassword()).equals("")) {
            newPasswordTitle1.setText(" ");
            jPasswordField1.setVisible(false);
        }
    }//GEN-LAST:event_jInputPasswordFocusGained

    private void jInputPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInputPasswordFocusLost
        if (String.valueOf(jInputPassword.getPassword()).equals("")) {
            jInputPassword.setText("jPasswordField1");
            jInputPassword.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_jInputPasswordFocusLost

    private void nameUserFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameUserFieldKeyTyped
        if (nameUserField.getText().length() > 30) {
            evt.consume();
        }
    }//GEN-LAST:event_nameUserFieldKeyTyped

    private void jInputPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jInputPasswordKeyTyped
        if (evt.getKeyChar() > 32 && evt.getKeyChar() < 256) {
            passwordSize += 1;
        } else if (evt.getKeyChar() == 8) {
            passwordSize = passwordSize - 1;
        }
        if (passwordSize < 0) {
            passwordSize = 0;
        }
        if (!String.valueOf(jInputPassword.getPassword()).equals("jPasswordField1")) {
            System.out.println("-->" + passwordSize);
            if (passwordSize > 5) {
                newPasswordTitle1.setText("REINGRESE LA CONTRASEÑA");
                defaultEditable(jPasswordField1);
                jPasswordField1.setVisible(true);
                jSaveForm.setEnabled(true);
                changePassword = true;
            } else if (passwordSize < 6) {
                newPasswordTitle1.setText(" ");
                jPasswordField1.setVisible(false);
                changePassword = false;
                //jSaveForm.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jInputPasswordKeyTyped

    private void chooseMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseMaleActionPerformed
        if (chooseMale.isSelected()) {
            userGender = 1;
            UserImage.setIcon(iconMale);
            chooseFemale.setSelected(false);
        } else {
            chooseMale.setSelected(true);
        }
    }//GEN-LAST:event_chooseMaleActionPerformed

    private void chooseFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFemaleActionPerformed
        if (chooseFemale.isSelected()) {
            userGender = 2;
            UserImage.setIcon(iconFemale);
            chooseMale.setSelected(false);
        } else {
            chooseFemale.setSelected(true);
        }
    }//GEN-LAST:event_chooseFemaleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserImage;
    private javax.swing.JRadioButton chooseFemale;
    private javax.swing.JRadioButton chooseMale;
    private javax.swing.JPanel jContent;
    private javax.swing.JButton jEditForm;
    private javax.swing.JPanel jForm;
    private javax.swing.JPasswordField jInputPassword;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton jSaveForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jUserLabel;
    private javax.swing.JLabel jWarning;
    private javax.swing.JLabel leftBackGround;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameUserField;
    private javax.swing.JLabel newPasswordTitle1;
    private javax.swing.JLabel passwordTitle;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JLabel phoneNumber1;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JLabel rightBackGround;
    private javax.swing.JPanel sectionHeader;
    private javax.swing.JLabel sectionTitle;
    private javax.swing.JTextArea textLastConection;
    private javax.swing.JTextArea textLastUpDate;
    // End of variables declaration//GEN-END:variables
}
