package com.graphyinterface.menus;

import com.graphyinterface.Home;
import com.model.User;
import com.model.Vehicle;
import data.functions.GenericFunctions;
import java.awt.Color;

public class VSavedVehiclesPanelEditScreen extends javax.swing.JFrame {

    private Vehicle vehicle;
    private User user;

    /**
     * Creates new form VSavedVehiclesPanelEditScreen
     *
     * @param selectedVehicle
     */
    public VSavedVehiclesPanelEditScreen(Vehicle selectedVehicle, User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        vehicle = selectedVehicle;
        this.user = user;
        for (int i = 0; i < 4; i++) {
            String item = comboBoxTypeVehicle.getItemAt(i);
            if (item.equalsIgnoreCase(selectedVehicle.getType())) {
                comboBoxTypeVehicle.setSelectedIndex(i);
                System.out.println("**Set");
                break;
            } else {
                System.out.println("No set");
            }
        }
        jTextVehicleModel.setText(selectedVehicle.getModel());
        jTextVehiclePerformance.setText(String.valueOf(selectedVehicle.getPerformance()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editBackGround = new javax.swing.JPanel();
        editFormPanel = new javax.swing.JPanel();
        sectionTitle = new javax.swing.JLabel();
        typeTitle = new javax.swing.JLabel();
        comboBoxTypeVehicle = new javax.swing.JComboBox<>();
        modelTitle = new javax.swing.JLabel();
        jTextVehicleModel = new javax.swing.JTextField();
        performanceTitle = new javax.swing.JLabel();
        jTextVehiclePerformance = new javax.swing.JTextField();
        jCheckBoxSelectDefault = new javax.swing.JCheckBox();
        jSaveVehicleButton = new javax.swing.JButton();
        jWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 520));
        setResizable(false);

        editBackGround.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true), javax.swing.BorderFactory.createMatteBorder(30, 30, 90, 30, new javax.swing.ImageIcon(getClass().getResource("/com/Images/carroretrociudad (1).jpg"))))); // NOI18N
        editBackGround.setPreferredSize(new java.awt.Dimension(340, 495));

        editFormPanel.setBackground(new java.awt.Color(255, 255, 255));
        editFormPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        editFormPanel.setPreferredSize(new java.awt.Dimension(272, 370));

        sectionTitle.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        sectionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sectionTitle.setText("EDITA TUS VEHICULOS");

        typeTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        typeTitle.setText("TIPO DE VEHICULO");

        comboBoxTypeVehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Carro", "Motocicleta", "Camioneta" }));

        modelTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        modelTitle.setText("REFERENCIA DEL VEHICULO");

        jTextVehicleModel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(180, 180, 180)));

        performanceTitle.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        performanceTitle.setText("RENDIMIENTO");

        jTextVehiclePerformance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextVehiclePerformance.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(180, 180, 180)));
        jTextVehiclePerformance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextVehiclePerformanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextVehiclePerformanceFocusLost(evt);
            }
        });
        jTextVehiclePerformance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextVehiclePerformanceKeyTyped(evt);
            }
        });

        jCheckBoxSelectDefault.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jCheckBoxSelectDefault.setText("Vehiculo Predeterminado");
        jCheckBoxSelectDefault.setToolTipText("Seleccionar por Defecto");
        jCheckBoxSelectDefault.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jSaveVehicleButton.setBackground(new java.awt.Color(0, 0, 0));
        jSaveVehicleButton.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jSaveVehicleButton.setForeground(new java.awt.Color(255, 255, 255));
        jSaveVehicleButton.setText("GUARDAR");
        jSaveVehicleButton.setPreferredSize(new java.awt.Dimension(100, 35));
        jSaveVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveVehicleButtonActionPerformed(evt);
            }
        });

        jWarning.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jWarning.setForeground(new java.awt.Color(255, 51, 51));
        jWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jWarning.setText(" ");

        javax.swing.GroupLayout editFormPanelLayout = new javax.swing.GroupLayout(editFormPanel);
        editFormPanel.setLayout(editFormPanelLayout);
        editFormPanelLayout.setHorizontalGroup(
            editFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFormPanelLayout.createSequentialGroup()
                .addGroup(editFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editFormPanelLayout.createSequentialGroup()
                        .addGroup(editFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editFormPanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jSaveVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(editFormPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(editFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxTypeVehicle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(typeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(modelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextVehicleModel)
                                    .addComponent(performanceTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextVehiclePerformance, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(editFormPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(editFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sectionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxSelectDefault, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        editFormPanelLayout.setVerticalGroup(
            editFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sectionTitle)
                .addGap(28, 28, 28)
                .addComponent(typeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxTypeVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(performanceTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextVehiclePerformance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jCheckBoxSelectDefault)
                .addGap(18, 18, 18)
                .addComponent(jSaveVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jWarning)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout editBackGroundLayout = new javax.swing.GroupLayout(editBackGround);
        editBackGround.setLayout(editBackGroundLayout);
        editBackGroundLayout.setHorizontalGroup(
            editBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editBackGroundLayout.setVerticalGroup(
            editBackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editBackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextVehiclePerformanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextVehiclePerformanceFocusGained
        if (jTextVehiclePerformance.getText().equals("Km/Galon")) {
            jTextVehiclePerformance.setText("");
            jTextVehiclePerformance.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jTextVehiclePerformanceFocusGained

    private void jTextVehiclePerformanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextVehiclePerformanceFocusLost
        if (jTextVehiclePerformance.getText().equals("")) {
            jTextVehiclePerformance.setText("Km/Galon");
            jTextVehiclePerformance.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_jTextVehiclePerformanceFocusLost

    private void jTextVehiclePerformanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextVehiclePerformanceKeyTyped
        GenericFunctions.inputOnlyNumber(evt);
    }//GEN-LAST:event_jTextVehiclePerformanceKeyTyped

    private void jSaveVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveVehicleButtonActionPerformed
        if (!comboBoxTypeVehicle.getSelectedItem().toString().equals("Seleccionar") && !jTextVehicleModel.getText().isBlank()
                && Double.parseDouble(jTextVehiclePerformance.getText()) > 0) {
            vehicle.setType(String.valueOf(comboBoxTypeVehicle.getSelectedItem()));
            vehicle.setModel(String.valueOf(jTextVehicleModel.getText()));
            vehicle.setPerformance(Double.parseDouble(jTextVehiclePerformance.getText()));
            if (jCheckBoxSelectDefault.isSelected()) {
                user.setDefaultVehicle(vehicle);
            }
            Home.defaultWarningLabel(" ", jWarning);
            Home.msgSucessfulAction("Datos Actualizados");
            this.dispose();
        }else{
            if(Double.parseDouble(jTextVehiclePerformance.getText()) < 1){
                jWarning.setText("El Rendimiento no puede ser 0");
            }else{
                jWarning.setText("Complete todos los campos");
            }
            
        }

    }//GEN-LAST:event_jSaveVehicleButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxTypeVehicle;
    private javax.swing.JPanel editBackGround;
    private javax.swing.JPanel editFormPanel;
    private javax.swing.JCheckBox jCheckBoxSelectDefault;
    private javax.swing.JButton jSaveVehicleButton;
    private javax.swing.JTextField jTextVehicleModel;
    private javax.swing.JTextField jTextVehiclePerformance;
    private javax.swing.JLabel jWarning;
    private javax.swing.JLabel modelTitle;
    private javax.swing.JLabel performanceTitle;
    private javax.swing.JLabel sectionTitle;
    private javax.swing.JLabel typeTitle;
    // End of variables declaration//GEN-END:variables
}
